Repository ismaxim/urling, pull requests merged in 2021-03, with the labels that each got.

#4 docs: update README
  README.md
  assets/hero-image.png
Labels: documentation

#5 ci: add notifications section into Travis config
  .travis.yml
Labels: ci

#7 feat: Add GitHub Actions on the project
  .github/workflows/main.yml
  .travis.yml
  composer.json
Labels: ci

#6 chore: init task-17-fix-static-analysis-errors
  .github/workflows/main.yml
  .travis.yml
  composer.json
  src/Urling/Core/Utilities/Editors/BasePartEditor.php
  src/Urling/Core/Utilities/Editors/BaseUrlEditor.php
  src/Urling/Core/Utilities/Misc/IntelliExceptions/Exceptions/ExceptionParserInterface.php
  src/Urling/Core/Utilities/Misc/IntelliExceptions/Exceptions/InexistentContextException.php
  src/Urling/Core/Utilities/Misc/IntelliExceptions/Exceptions/UnsupportedMethodException.php
  src/Urling/Core/Utilities/Misc/IntelliExceptions/IntelliExceptions.php
  src/Urling/Core/Utilities/PartParsers/Storages/AliasesStorage.php
  src/Urling/Core/Utilities/PartParsers/Storages/GluingsStorage.php
  src/Urling/Core/Utilities/PartParsers/Storages/NamesStorage.php
  src/Urling/Core/Utilities/PartParsers/Storages/NamespacesStorage.php
  src/Urling/Core/Utilities/UrlParser.php
  src/Urling/PartParsers/PathParser.php
  src/Urling/PartParsers/QueryParser.php
Labels: fix

#3 feat: add static analysis - phpstan
  .github/workflows/main.yml
  composer.json
  phpstan.neon.dist
  src/Urling/Core/Utilities/Editors/BasePartEditor.php
  src/Urling/Core/Utilities/Editors/BaseUrlEditor.php
  src/Urling/Core/Utilities/Misc/IntelliExceptions/Exceptions/ExceptionParserInterface.php
  src/Urling/Core/Utilities/Misc/IntelliExceptions/Exceptions/InexistentContextException.php
  src/Urling/Core/Utilities/Misc/IntelliExceptions/Exceptions/UnsupportedMethodException.php
  src/Urling/Core/Utilities/Misc/IntelliExceptions/IntelliExceptions.php
  src/Urling/Core/Utilities/PartParsers/Storages/AliasesStorage.php
  src/Urling/Core/Utilities/PartParsers/Storages/GluingsStorage.php
  src/Urling/Core/Utilities/PartParsers/Storages/NamesStorage.php
  src/Urling/Core/Utilities/PartParsers/Storages/NamespacesStorage.php
  src/Urling/Core/Utilities/UrlParser.php
  src/Urling/PartParsers/PathParser.php
  src/Urling/PartParsers/QueryParser.php
Labels: static analysis
